version: '3'

services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-network

  strapi:
    build: .
    container_name: strapi-app
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
    ports:
      - 1337:1337
    volumes:
      - ./src:/app/src   #Make sure content types are synced with local
    depends_on:
      - postgres
    networks:
      - strapi-network

  nginx:
    image: nginx:latest
    container_name: strapi-nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-network

volumes:
  postgres-data:

networks:
  strapi-network:
    driver: bridge
