version: '3'

services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-network

  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev       #  Use dev Dockerfile
    container_name: strapi-app
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
    ports:
      - 1337:1337
    volumes:
      - ./src:/app/src                 #  Sync content-types
      - ./config:/app/config           #  Sync config changes if needed
      - ./public:/app/public           #  Sync public assets if needed
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - postgres
    networks:
      - strapi-network

  nginx:
    image: nginx:latest
    container_name: strapi-nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-network

volumes:
  postgres-data:

networks:
  strapi-network:
    driver: bridge
