version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "strapi-task1"
        LoadBalancerInfo:
          ContainerName: "strapi"
          ContainerPort: 1337
#run