version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "strapi-task1"
        LoadBalancerInfo:
          ContainerName: "strapi"
          ContainerPort: 1337

Hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root

  AfterAllowTestTraffic:
    - location: scripts/verify.sh
      timeout: 300
      runas: root
