name: Build, Push Docker & Deploy with Terraform

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4

      - name:  Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name:  Build Docker Image
        run: docker build -t strapi-app:latest .

      - name:  Tag Docker Image
        run: docker tag strapi-app:latest mansibite/strapi-app:latest

      - name:  Push Docker Image
        run: docker push mansibite/strapi-app:latest

      - name:  Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name:  Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name:  Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
